- hosts: all
  name: Get Host informations
  gather_facts: true
  tasks:
    - name: Get passwd database
      getent:
        database: passwd
    - debug:
        var: ansible_facts.getent_passwd

    - name: Get shadow database
      become: true
      getent:
        database: shadow
    - debug:
        var: ansible_facts.getent_shadow

    - name: Get Hosts database
      getent:
        database: hosts
    - debug:
        var: ansible_facts.getent_hosts

    - name: Get Group database
      getent:
        database: group
    - debug:
        var: ansible_facts.getent_group