- hosts: all
  name: Get Host informations
  gather_facts: true
  tasks:
    - debug:
        msg: "Ansible host is : {{ ansible_host }} et ansible name : {{ inventory_hostname }} "
    - name: Test connexion
      ping:

    - name: Gcat et passwd database
      getent:
        database: passwd
    - debug:
        var: ansible_facts.getent_passwd

    - name: Get shadow database
      become: true
      getent:
        database: shadow
    - debug:
        var: ansible_facts.getent_shadow

    - name: Get Hosts database
      getent:
        database: hosts
    - debug:
        var: ansible_facts.getent_hosts

    - name: Get Group database
      getent:
        database: group
    - debug:
        var: ansible_facts.getent_group

    - name: Test loop ansible_facts.getent_passwd
      debug:
        msg: "Print user : {{ item }} et uid : {{ ansible_facts.getent_passwd[item][1] }} et shell : {{ ansible_facts.getent_passwd[item][5] }}  et shell : {{ ansible_facts.getent_passwd[item][4] }}"
      when: "({{ ansible_facts.getent_passwd[item][1] }} >= 1000) and ('nologin' not in ansible_facts.getent_passwd[item][5] )"
      with_items: "{{ ansible_facts.getent_passwd }}"

    - name: Set alla facts
      set_fact:
        getent_passwd: ansible_facts.getent_passwd
        getent_shadow: ansible_facts.getent_shadow
        getent_hosts: ansible_facts.getent_hosts
        getent_group: ansible_facts.getent_group

