---
- hosts: all
  become: true

  vars:
    cheat_version: "4.2.0"
    cheat_type: "cheat-linux-amd64"

  tasks:
    - name: Gcat et passwd database
      getent:
        database: passwd
    - debug:
        var: ansible_facts.getent_passwd

  roles:
    - role: install_cheatsheet