---
- hosts: all
  become: true
  gather_facts: false

  vars:
    cheat_version: "4.2.0"
    cheat_type: "cheat-linux-amd64"

  tasks:
    - name: download Cheatsheet archive
      get_url:
        url: "https://github.com/cheat/cheat/releases/download/{{ cheat_version }}/{{ cheat_type }}.gz"
        dest: "/tmp/{{ cheat_type }}.gz"
      notify: unarchive cheatsheet

    - name: Create cheatsheet conf directory
      file:
        path: /etc/cheat
        state: directory
        owner: root
        group: root
        mode: '0755'

  handlers:
    - name: unarchive cheatsheet
      unarchive:
        path: "/tmp/{{ cheat_type }}.gz"
        remote_src: yes
        dest: /usr/bin/cheat
      notify: Make cheat readable

    - name: Make cheat readable
      file:
        path: /usr/bin/cheat
        owner: root
        group: root
        mode: '0755'
