---
- name: issue.net
  include_tasks: setup_issue.yml
  tags:
    - issue
    - motd

- name: Config NTP
  include_tasks: timezone.yml
  tags:
    - ntp

- name: Install personalisation 
  include_tasks: user_personalisation.yml
  tags: 
    - perso