---
- name: issue.net
  include_tasks: setup_issue.yml
  tags:
    - issue
    - motd

- name: Config NTP
  include_tasks: timezone.yml
  tags:
    - ntp

- name: Install personalisation 
  include_tasks: user_personalisation.yml
  tags: 
    - perso

- name: install vim plugin
  include_tasks: vim_plugin.yml
  tags: 
    - vim 
    - perso 

- name: Configure ZSH 
  include_tasks: configure_zsh.yml
  when: '"zsh" in default_shell'
  tags: 
    - zsh 
    - perso