---
- name: Setup issue.net file
  copy:
    src: issue.net
    dest: /etc/issue.net
    force: yes

- name: Setup issue file
  copy:
    src: issue.net
    dest: /etc/issue
    force: yes

- name: Print banner on ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: Banner /etc/issue.net

- name: Restart ssh service
  service:
    name: sshd
    state: reloaded
