---
- name: Activate ntp
  service:
    name: chronyd
    state: started
    enabled: yes
  tags:
    - ntp

- name: Set Timezone 
  community.general.timezone: 
    name: "{{ ntp_default_zone }}/{{ ntp_defautl_city }}"