---
- name: Activate ntp
  service:
    name: chronyd
    state: started
    enabled: yes
  when: ansible_os_family == "Centos"
  tags:
    - ntp
  
- name: Activate ntp for debian 
  service:
    name: systemd-timesyncd
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"
  tags:
    - ntp

- name: Set Timezone 
  community.general.timezone: 
    name: "{{ ntp_default_zone }}/{{ ntp_defautl_city }}"