- name: install defaults app 
  ansible.builtin.apt: 
    name: "{{ item }}"
  with_items: "{{ default_applications }}"
  when: ansible_os_family == 'Debian'

- name: Block for RHEL based OS
  block: 
    - name: install epel Releases 
      ansible.builtin.yum: 
        name: epel-release
    - name: install defaults app 
      ansible.builtin.yum: 
        name: "{{ item }}"
      with_items: "{{ default_applications }}"
  when: ansible_os_family == "RedHat"

- name: Retrieve all users 
  ansible.builtin.include_role: 
    name: role-get-real-user

- name: Setup {{ default_shell }} for user when installed
  ansible.builtin.user:
    name: "{{ item.key }}"
    shell: "{{ default_shell }}"
  with_items: "{{ real_users }}" 
  become: true

  
