---
- name: Gather the package facts
  package_facts:
    manager: auto

- name: Print the package facts
  ansible.builtin.debug:
    var: ansible_facts.packages

- name: Check whether a package called foobar is installed
  ansible.builtin.debug:
    msg: "{{ ansible_facts.packages['vim'] | length }} versions of vim are installed!"
  when: "'vim' in ansible_facts.packages"
