---
- name: Install git vim for RHEL
  yum:
    name:
      - git
      - vim
    state: present
  when: ansible_os_family == "RedHat"
  become: true

- name: Install git vim for DEBIAN
  apt:
    pkg:
      - git
      - vim
    state: present
  when: ansible_os_family == "Debian"
  become: true
