---
- name: test
  debug:
    var: ansible_facts
    
- name: Install git vim for RHEL
  yum:
    name:
      - git
      - vim
    state: present
  when: ansible_facts['os_family'] == "RedHat"
  become: true

- name: Install git vim for DEBIAN
  apt:
    pkg:
      - git
      - vim
    state: present
  when: ansible_facts['os_family'] == "Debian"
  become: true
