---
- include_tasks: install_package.yml

- name: Download PaperColor
  git:
    repo: "https://github.com/NLKNguyen/papercolor-theme.git"
    dest: /usr/share/vim/vim80/pack/colors/start/papercolor-theme
  when: default_color_theme == 'PaperColor'
  become: true

- name: write user's .vimrc
  template:
    src: templates/.vimrc.j2
    dest: "{{ ansible_facts.getent_passwd[item][4] }}/.vimrc"
    group: "{{ item }}"
    owner: "{{ item }}"
    mode: 0644
  when: "({{ ansible_facts.getent_passwd[item][1] }} >= 1000) and ('nologin' not in ansible_facts.getent_passwd[item][5] )"
  with_items: "{{ ansible_facts.getent_passwd }}"
  become: true

- name: write root's .vimrc
  template:
    src: templates/.vimrc.j2
    dest: /root/.vimrc
    group: root
    owner: root"
    mode: 0644
  become: true

